# Generated by Django 4.2.29 on 2026-04-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail_address',
            field=models.EmailField(blank=True, help_text='Email Gmail để nhận thông báo và khôi phục mật khẩu (tùy chọn)', max_length=254, null=True, verbose_name='Email Gmail'),
        ),
    ]
