"""
Django settings for due_book project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib import messages
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    # 'whitenoise.runserver_nostatic',  # Tùy chọn: Chỉ cần nếu muốn Whitenoise thay thế Django's runserver trong development

    #===== LOCAL APPS =====
    'users.apps.UsersConfig',
    'books',
    'ratings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ← THÊM: Phải đặt SAU SecurityMiddleware, TRƯỚC SessionMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'due_book.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Cấu hình user register
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'custom_filters': 'books.templatetags.custom_filters',
            },
        },
    },
]

WSGI_APPLICATION = 'due_book.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# ==================== DATABASE CONFIGURATION ====================
# Ưu tiên: 1) DATABASE_URL (Render), 2) DB_ENGINE config, 3) SQLite fallback

import dj_database_url

# Render tự động cung cấp DATABASE_URL khi có PostgreSQL service
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    print("Using PostgreSQL from DATABASE_URL (Render)")
elif os.getenv('DB_ENGINE') == 'django.db.backends.postgresql':
    # PostgreSQL Configuration (Manual/Docker)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'due_book_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'postgres123'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
    print("Using PostgreSQL from manual config")
else:
    # SQLite Configuration (Development/Fallback)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("Using SQLite (development)")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]



# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'vi-vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Thư mục chứa static files trong development
STATICFILES_DIRS = [BASE_DIR / 'static']

# Thư mục collectstatic cho production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Static files storage cho Whitenoise (production)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Media files (uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==================== MESSAGE TAGS ====================
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# ==================== AUTHENTICATION SETTINGS ====================
# URL để redirect khi user chưa đăng nhập nhưng truy cập trang @login_required
LOGIN_URL = 'users:user_login'

# URL để redirect sau khi đăng nhập thành công
LOGIN_REDIRECT_URL = 'books:home'

# URL để redirect sau khi đăng xuất
LOGOUT_REDIRECT_URL = 'books:home'

# ==================== EMAIL SETTINGS ====================
# Ưu tiên: 1) SendGrid API (Render production), 2) SMTP Gmail (local), 3) Console (dev)

# Check if SendGrid API key is available
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')

if SENDGRID_API_KEY:
    # Production: Use SendGrid API (works on Render free tier)
    EMAIL_BACKEND = 'due_book.sendgrid_backend.SendGridBackend'
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'DUE Book <noreply@due-book.onrender.com>')
    print(f"✅ Using SendGrid API backend")
else:
    # Fallback: SMTP or Console
    EMAIL_HOST_USER_ENV = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD_ENV = os.getenv('EMAIL_HOST_PASSWORD')

    if not DEBUG:
        # Production without SendGrid: Try SMTP
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        print("⚠️ Using SMTP backend (production, no SendGrid)")
    else:
        # Development: Use SMTP if configured, otherwise Console
        HAS_SMTP_CREDENTIALS = all([
            EMAIL_HOST_USER_ENV,
            EMAIL_HOST_PASSWORD_ENV,
        ])

        if HAS_SMTP_CREDENTIALS:
            EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
            print("🔧 Using SMTP backend (development with credentials)")
        else:
            EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
            print("💻 Using Console backend (development/no config)")

    # SMTP Configuration (chỉ dùng khi không có SendGrid)
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    try:
        EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    except (ValueError, TypeError):
        EMAIL_PORT = 587
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = EMAIL_HOST_USER_ENV
    EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD_ENV

    if EMAIL_HOST_USER_ENV:
        DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', f'DUE Book <{EMAIL_HOST_USER_ENV}>')
    else:
        DEFAULT_FROM_EMAIL = 'DUE Book <noreply@example.com>'

# Site URL cho password reset
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

