# Generated by Django 4.2.29 on 2026-04-08 15:15

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(error_messages={'max_length': 'Tên sách không được vượt quá 300 ký tự.'}, max_length=300, validators=[books.models.validate_title_length], verbose_name='Tên sách'),
        ),
    ]
